Add new test cases
Adds two new test cases

diff --git a/.github/workflows/dai-testing.yml b/.github/workflows/dai-testing.yml
--- a/.github/workflows/dai-testing.yml
+++ b/.github/workflows/dai-testing.yml
@@ -147,4 +147,47 @@ jobs:
           sudo dmesg -C
           make remove
 
+      
+      # Test Case 3
+      # Insert the Kernel Module
+      - name: Insert Kernel Module
+        run: make install
+
+      - name: Test An entry exists in the ARP table for the ARP request
+       # Expects Packet to be accepted even without DHCP snooping
+        run: |
+          #Assign static MAC addresses to veth0 and veth3
+          sudo ip netns exec ns1 ip link set veth0 down
+          sudo ip netns exec ns1 ip link set veth0 address 11:33:55:77:99:11
+          sudo ip netns exec ns1 ip link set veth0 up
+
+          sudo ip netns exec ns2 ip link set veth3 down
+          sudo ip netns exec ns2 ip link set veth3 address 00:22:44:66:88:00
+          sudo ip netns exec ns2 ip link set veth3 up
+
+          # Run the ARP Request and Response script
+          sudo ip netns exec ns1 python3 ./tests/ARP_Request_And_Response.py
+          
+          # Check dmesg logs for the ARP drop status
+          ARP_DROP_STATUS=$(sudo dmesg | grep "ARP RETURN status was: NF_ACCEPT")
+          
+          # Print the dmesg log for debugging purposes
+          sudo echo "dmesg logs:"
+          sudo dmesg | tail -n 20  # Print the last 20 lines of dmesg
+          
+          # If ARP ACCEPET was fund, then Test passed
+          if [ -n "$ARP_DROP_STATUS" ]; then
+            sudo echo "Test Passed!"
+          else
+            sudo echo "The ARP Request was not met with a response"
+            sudo echo "Test Failed!"
+            exit 1
+          fi
+
+        # Remove Module
+      - name: Clean Up Test
+        run: |
+          sudo dmesg -C
+          make remove
+
 
